# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d018d949bdbee6da089c650e735812b14c66a4af38ff287ec44246f304a52f6850820534b5b736297f50b9f7ea1fa71358920e5527670de081060297f235f6d3

test:
  secret_key_base: b437ec7b5089253669281f95305afb1774d767d409416b0067a6dc435dd23bb1a247cb4cd3aaa5e5f41cdacd016bd167a3342cc7550b837c2a0a65ae4886f006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
